jobs:
- job: 'Build_Native'
  strategy:
    matrix:
      Linux:
        image.name: 'ubuntu-16.04'
      Mac:
        image.name: 'macOS-10.13'
      Windows:
        image.name: 'windows-2019'
    maxParallel: 3
  pool:
    vmImage: '$(image.name)'
  steps:
  - script: |
      sudo apt-get -y update
      sudo apt-get -y install g++-multilib
      /bin/sh ./build.sh -32bit
    condition: startsWith(variables['image.name'], 'ubuntu')
    displayName: 'Building/moving native code (Linux).'
  - script: |
      /bin/sh ./build.sh -32bit
    condition: startsWith(variables['image.name'], 'macOS')
    displayName: 'Building/moving native code (Mac).'
  - script: |
      set PATH=%PATH%;C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\
      .\build.bat -32bit
    condition: startsWith(variables['image.name'], 'windows')
    displayName: 'Building/moving native code. (Windows)'
  - task: CopyFiles@2
    condition: succeeded()
    inputs:
      sourceFolder: staging
      contents: '*'
      targetFolder: '$(Build.ArtifactStagingDirectory)'
    displayName: 'Move binary to staging'
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: $(Build.ArtifactStagingDirectory)
      artifactName: native-$(image.name)
    displayName: 'Publish native library'

- job: 'Test_Native'
  dependsOn: 'Build_Native'
  strategy:
    matrix:
      Linux:
        image.name: 'ubuntu-16.04'
      Mac:
        image.name: 'macOS-10.13'
      Windows:
        image.name: 'windows-2019'
    maxParallel: 3
  pool:
    vmImage: '$(image.name)'
  steps:
  - task: DownloadBuildArtifacts@0
    inputs:
      buildType: 'current'
      downloadType: 'specific'
    displayName: 'Download build artifacts'
  - task: CopyFiles@2
    inputs:
      sourceFolder: '$(System.ArtifactsDirectory)'
      contents: '**/lib_ebmcore_*'
      targetFolder: 'staging'
      flattenFolders: true
    displayName: 'Move binary to staging directory'
  - script: |
      sudo apt-get -y update
      sudo apt-get -y install g++-multilib
      /bin/sh ./tests/core/test_core_api.sh -nobuildcore
    condition: startsWith(variables['image.name'], 'ubuntu')
    displayName: 'Testing native code (Linux).'
  - script: |
      /bin/sh ./tests/core/test_core_api.sh -nobuildcore
    condition: startsWith(variables['image.name'], 'macOS')
    displayName: 'Testing native code (Mac).'
  - script: |
      set PATH=%PATH%;C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\
      .\tests\core\test_core_api.bat -nobuildcore
    condition: startsWith(variables['image.name'], 'windows')
    displayName: 'Testing native code. (Windows)'

- job: 'Build_JS_Inline'
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.6'
      architecture: 'x64'
  - script: python build-js-bundles.py devops
    workingDirectory: 'python/scripts'
    displayName: 'Build JS bundle'
  - task: CopyFiles@2
    condition: succeeded()
    inputs:
      sourceFolder: 'python/interpret-core/interpret/lib'
      contents: 'interpret-inline.js'
      targetFolder: '$(Build.ArtifactStagingDirectory)'
    displayName: 'Move assets to staging'
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: $(Build.ArtifactStagingDirectory)
      artifactName: interpret-inline-bundle
    displayName: 'Publish interpret inline library'

- job: 'Build_Package'
  dependsOn: ['Build_Native', 'Build_JS_Inline']
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - task: DownloadBuildArtifacts@0
    inputs:
      buildType: 'current'
      downloadType: 'specific'
    displayName: 'Download build artifacts'
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.6'
      architecture: 'x64'
  - script: python -m pip install --upgrade pip setuptools wheel
    displayName: 'Install tools'
  - task: CopyFiles@2
    inputs:
      sourceFolder: '$(System.ArtifactsDirectory)'
      contents: '**/lib_ebmcore_*'
      targetFolder: 'python/interpret-core/interpret/lib'
      flattenFolders: true
    displayName: 'Move binary to Python layer'
  - task: CopyFiles@2
    inputs:
      sourceFolder: '$(System.ArtifactsDirectory)'
      contents: '**/interpret-inline.js'
      targetFolder: 'python/interpret-core/interpret/lib'
      flattenFolders: true
    displayName: 'Move Interpret inline to Python layer'
  - script: python setup.py bdist_wheel -d ../../staging
    condition: succeeded()
    workingDirectory: 'python/interpret-core'
    displayName: 'Build wheel (interpret-core)'
  - script: python setup.py bdist_wheel -d ../../staging
    condition: succeeded()
    workingDirectory: 'python/interpret'
    displayName: 'Build wheel (interpret)'
  - task: CopyFiles@2
    condition: succeeded()
    inputs:
      sourceFolder: staging
      contents: '*.whl'
      targetFolder: '$(Build.ArtifactStagingDirectory)/wheel'
    displayName: 'Move wheel for Build Artifact'
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)/wheel'
      artifactName: 'wheel'
    displayName: 'Publish wheel as Build Artifact'

- job: 'Test'
  dependsOn: 'Build_Package'
  strategy:
    matrix:
      LinuxPython35:
        python.version: '3.5'
        image.name: 'ubuntu-16.04'
      LinuxPython36:
        python.version: '3.6'
        image.name: 'ubuntu-16.04'
      LinuxPython37:
        python.version: '3.7'
        image.name: 'ubuntu-16.04'
#      WindowsPython35:
#        python.version: '3.5'
#        image.name: 'windows-2019'
      WindowsPython36:
        python.version: '3.6'
        image.name: 'windows-2019'
      WindowsPython37:
        python.version: '3.7'
        image.name: 'windows-2019'
      MacPython35:
        python.version: '3.5'
        image.name: 'macOS-10.13'
      MacPython36:
        python.version: '3.6'
        image.name: 'macOS-10.13'
      MacPython37:
        python.version: '3.7'
        image.name: 'macOS-10.13'
    maxParallel: 9
  pool:
    vmImage: '$(image.name)'
  steps:
  - task: DownloadBuildArtifacts@0
    inputs:
      buildType: 'current'
      downloadType: 'specific'
    displayName: 'Download build artifacts'
  - task: CopyFiles@2
    inputs:
      sourceFolder: '$(System.ArtifactsDirectory)'
      contents: '**/lib_ebmcore_*'
      targetFolder: 'python/interpret-core/interpret/lib'
      flattenFolders: true
    displayName: 'Move binary to Python layer'
  - task: CopyFiles@2
    inputs:
      sourceFolder: '$(System.ArtifactsDirectory)'
      contents: '**/interpret-inline.js'
      targetFolder: 'python/interpret-core/interpret/lib'
      flattenFolders: true
    displayName: 'Move Interpret inline to Python layer'
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'
  - script: python -m pip install --upgrade pip setuptools wheel
    displayName: 'Install tools'
  - script: |
      python -m pip install numpy scipy
    workingDirectory: python/interpret-core
    displayName: 'Install numpy/scipy first for mis-specified pip packages.'
  - script: |
      mkdir -p ~/.matplotlib
      echo "backend: TkAgg" >> ~/.matplotlib/matplotlibrc
    condition: startsWith(variables['image.name'], 'macOS')
    displayName: 'Matplotlib patch for mac.'
  - script: |
      python -m pip install -r dev-requirements.txt
    workingDirectory: python/interpret-core
    displayName: 'Install requirements (Windows)'
    condition: startsWith(variables['image.name'], 'windows')
  - script: |
      python -m pip install -r dev-requirements.txt
    workingDirectory: python/interpret-core
    displayName: 'Install requirements (Linux/Mac)'
    condition: or(startsWith(variables['image.name'], 'ubuntu'), startsWith(variables['image.name'], 'macOS'))
  - script: |
      set PATH=%PATH%;%GeckoWebDriver%
      python -m pytest -vv -n auto --runslow --runselenium --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
    workingDirectory: python/interpret-core
    condition: startsWith(variables['image.name'], 'windows')
    displayName: 'Run pytest (Windows)'
  - script: |
      python -m pytest -vv -n auto --runslow --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
    workingDirectory: python/interpret-core
    condition: or(startsWith(variables['image.name'], 'ubuntu'), startsWith(variables['image.name'], 'macOS'))
    displayName: 'Run pytest (Non-Windows)'
  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testResultsFiles: '**/test-*.xml'
      testRunTitle: 'Publish test results for Python $(python.version) at $(image.name)'
    displayName: 'Publish test results'
  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.xml'
      reportDirectory: '$(System.DefaultWorkingDirectory)/**/htmlcov'
    condition: startsWith(variables['image.name'], 'windows')
    displayName: 'Publish test coverage results'

- job: 'Publish_Package'
  dependsOn:
  - 'Test'
  - 'Test_Native'
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - task: DownloadBuildArtifacts@0
    inputs:
      buildType: 'current'
      downloadType: 'single'
      artifactName: 'wheel'
  - task: PublishPipelineArtifact@0
    inputs:
      sourceFolder: '$(System.ArtifactsDirectory)'
      artifactName: 'drop'
